/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_java_maven_test_wrap_Wrap */

#ifndef _Included_com_java_maven_test_wrap_Wrap
#define _Included_com_java_maven_test_wrap_Wrap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_java_maven_test_wrap_Wrap
 * Method:    seqpass
 * Signature: ([Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_java_maven_test_wrap_Wrap_seqpass
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
